config/routes.rb
ExportSimfyData::Application.routes.draw do

  get 'artists' => 'home#artists'

  get 'login' => 'session#login'
  post 'session/create' => 'session#create', :as => :create_session
  get 'logout' => 'session#logout'

  root :to => 'home#index'

end

app/controllers/application_controller.rb
require 'ostruct'

class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_session

  def current_session
    OpenStruct.new(session)
  end

  private
  
  def simfy
    Simfy.create_from_access_token(current_session.access_token)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def artists
    render :json => simfy.artists, :layout => false
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
  end

  def create
    simfy = Simfy.create_and_login(params[:login][:username], params[:login][:password])
    session[:username] = params[:login][:username]
    session[:access_token] = simfy.access_token
    redirect_to root_path
  end

  def logout
    reset_session
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    current_session.access_token.present?
  end
end

app/views/home/index.html.erb
<div class="container container-1">
  <div class="row-fluid">
    <span class="span4">
      <h2 class="heading">From</h2>
      <img src="/images/ec0e1767783987fb/source.jpg" class="pull-center image">
      <p>Product benefit number one.&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque lacinia elit, at gravida.</p>
    </span>
    <span class="span4">
      <p>After&nbsp;logging&nbsp;into both services we show you a preview of the data being copied over.</p>
      <h2 class="heading">
        <a href="/start">Start</a>
        <!-- <%= link_to "Artists", artists_path %> -->
      </h2>
    </span>
    <span class="span4">
      <h2 class="heading">To</h2>
      <img src="/images/af23645c515b28b5/source.jpeg" class="image">
      <p>Product benefit number one.&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque lacinia elit, at gravida.</p>
    </span>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<img src="/assets/bolt.png" class="pull-left image">
<a class="brand cke_focus" href="#">Music relocation services</a>
<ul class="nav pull-right">
  <li>
    <a href="#">Home</a>
    <!-- Logged in as <%= current_session.username %> - <%= link_to "logout", logout_path %> -->
  </li>
  <li>
    <a href="#">Tour</a>
  </li>
  <li>
    <a href="#">About</a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Limelight|Flamenco|Federo|Yesteryear|Josefin Sans|Spinnaker|Sansita One|Handlee|Droid Sans|Oswald:400,300,700" media="screen" rel="stylesheet" type="text/css" />
    <style>
      /* No content under the fixed bootstrap header. */
      body {
        padding-top: 60px;
      }
    </style>
    <title><%= content_for?(:title) ? yield(:title) : "Take your music library with you" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div class="container-fluid container-fluid-3">
      <div class="container">
        <div class="row-fluid">
          <span class="span12">
            <h1 class="heading">Take your music
              <br>library with you</h1>
            <p>Change streaming services with ease.</p>
            <button class="btn btn-large btn-primary">Try it now&nbsp;→</button>
          </span>
        </div>
      </div>
    </div>
    <div class="container container-1">
      <div class="row-fluid">
        <span class="span4">
          <h2 class="heading">From</h2>
          <img src="/assets/simfy_logo_neu.jpg" class="pull-center image">
          <p>Product benefit number one.&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque lacinia elit, at gravida.</p>
        </span>
        <span class="span4">
          <p>After&nbsp;logging&nbsp;into both services we show you a preview of the data being copied over.</p>
          <h2 class="heading">
            <a href="/start">Start</a>
          </h2>
        </span>
        <span class="span4">
          <h2 class="heading">To</h2>
          <img src="/assets/Unknown.jpeg" class="image">
          <p>Product benefit number one.&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque lacinia elit, at gravida.</p>
        </span>
      </div>
    </div>
    <div class="container-fluid container-fluid-1 container-fluid-2 container-fluid-4">
      <div class="container">
        <div class="row-fluid">
          <span class="span7">
            <div class="page-header">
              <h1>It's your data. <small contenteditable="true">Copy your music collection</small>

              </h1>
            </div>
            <p>Vivamus dapibus iaculis interdum. Aliquam tempor nisl sit amet sapien lobortis ac pulvinar sapien cursus. Nullam sed convallis tortor. Phasellus facilisis, ligula vel faucibus tempus,</p>
          </span>
          <span class="span5">
            <img src="/assets/400.jpeg" class="image">
          </span>
        </div>
      </div>
    </div>
    <div class="container-fluid container-fluid-2 container-fluid-5">
      <div class="container">
        <div class="row-fluid">
          <span class="span5">
            <img src="/assets/400.jpeg" class="image">
          </span>
          <span class="span7">
            <div class="page-header">
              <h1>Feature Number Two <small>This one is nice too</small>
              </h1>
            </div>
            <p>Vivamus dapibus iaculis interdum. Aliquam tempor nisl sit amet sapien lobortis ac pulvinar sapien cursus. Nullam sed convallis tortor. Phasellus facilisis, ligula vel faucibus tempus,</p>
          </span>
        </div>
      </div>
    </div>
    <div class="container-fluid container-fluid-1 container-fluid-2">
      <div class="container">
        <div class="row-fluid">
          <span class="span7">
            <div class="page-header">
              <h1>Feature Number Three <small>So good, you'll explode</small>
              </h1>
            </div>
            <p>Vivamus dapibus iaculis interdum. Aliquam tempor nisl sit amet sapien lobortis ac pulvinar sapien cursus. Nullam sed convallis tortor. Phasellus facilisis, ligula vel faucibus tempus,</p>
          </span>
          <span class="span5">
            <img src="/assets/400.jpeg" class="image">
          </span>
        </div>
      </div>
    </div>
    <div class="container container-2">
      <div class="row-fluid">
        <span class="span12">
          <p>Our philosophy here.&nbsp;Curabitur vel consequat tortor. Aliquam. Erat. Volutpat.</p>
        </span>
      </div>
    </div>
    <div class="container-fluid container-fluid-6">
      <div class="container">
        <div class="row-fluid">
          <span class="span12">
            <div class="pull-left">
              <p>© AwesomeCo</p>
            </div>
            <ul class="nav nav-pills pull-right">
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Privacy</a>
              </li>
              <li>
                <a href="#">Terms Of Service</a>
              </li>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/session/login.html.erb
<h1>Login</h1>

<%= form_for :login, :url => create_session_path do |form| %>
  <ul>
    <li>
      <%= form.label :username %>:
      <%= form.text_field :username %>
    </li>
    <li>
      <%= form.label :password %>:
      <%= form.password_field :password %>
    </li>
  </ul>
  <%= form.submit "Login" %>
<% end %>